### ISSUE TITLE
PrivacyMonth in Italy

### ISSUE THREAD

**Issue by Mte90** [edovio/RepsRegionalCoach#10]
## Objective Goal:
Organize events, get new likes/followers on social and engage with new people.

## Roles

* **R**esponsible: @mte90, @edovio

## Item list:
- [x] Post in the forum
- [x] Create 2 talk by the community
- [x] Organize at least 2 events
- [x] Finish the month about privacy

**Comment by Mte90** [comment]
Revision in progress of the tips to share online and of the slides https://public.etherpad-mozilla.org/p/mozita-privacymonth-2017

**Comment by edovio** [comment]
Finished Yesterday. Some results in this document -> https://public.etherpad-mozilla.org/p/mozita-privacymonth-2017
