### ISSUE TITLE
2017 participation plan

### ISSUE THREAD

**Issue by Mte90** [edovio/RepsRegionalCoach#4]
## Objective Goal:
Create the 2017 plan with all our ideas and schedule them

## Roles

* **R**esponsible: @mte90, @edovio
* **I**nformed: @flod

## Item list:
- [x] Create a list of all our ideas and activities
- [x] Develop the plan
- [x] Confirm the plan

**Comment by Mte90** [comment]
Plan in slides: https://docs.google.com/presentation/d/1bqDF6Vhhq3b3dIBdRzob5h7uLPljvqibpkc8F4qjsmc/edit#slide=id.p

**Comment by Mte90** [comment]
We need to confirm the plan officially

**Comment by edovio** [comment]
Plan made by me: https://docs.google.com/document/d/10ZzEElC6n_Qphho0sDC7BHz84drdhQe0TYus1ZM7q4A/edit?usp=sharing

**Comment by edovio** [comment]
Disccussed and approved with @Mte90 today

**Comment by edovio** [comment]
Need to be informed @flod

**Comment by Mte90** [comment]
I think that can be closed
