### ISSUE TITLE
Develop new mozillaitalia.github.io

### ISSUE THREAD

**Issue by Mte90** [edovio/RepsRegionalCoach#9]
## Objective Goal:
Create a new landing page to show what we do

## Related documents and links

* http://mozillaitalia.github.io/
* https://github.com/EugenioPetulla/mozillaitalia.github.io

## Roles

* **R**esponsible: @mte90
* **S**upporter: @edovio, @eugeniopetulla @gabrycaos 

## Item list:
- [ ] New design
- [ ] New links and sections
- [ ] Map of volunteers
- [ ] Link for a survey for feedbacks

**Comment by gabrycaos** [comment]
there is a specific template for making this?

**Comment by Mte90** [comment]
We are already working on this and waiting for @mirkopizii that finish on https://github.com/MirkoPizii/mozillaitalia.github.io and there are few tickets

**Comment by Mte90** [comment]
We are mantaining a document for that: https://public.etherpad-mozilla.org/p/mozita-sito-2017

**Comment by Mte90** [comment]
The new repo is https://github.com/EugenioPetulla/mozillaitalia.github.io

**Comment by Mte90** [comment]
I think that we can archive this one also because now we are working on new content for the actual website.
